project:
  title: "report"
  output-dir: "_output"

engine: julia  # Указываем движок Julia

execute:
  eval: true   # Включаем выполнение кода

standalone: true
self-contained: true

lang: ru-RU
number-sections: true
toc: true
toc-title: "Содержание"
toc-depth: 2

crossref:
  lof-title: "Список иллюстраций"
  lot-title: "Список таблиц"
  lol-title: "Листинги"

bibliography:
  - bib/cite.bib
csl: _resources/csl/gost-r-7-0-5-2008-numeric.csl

format:
  docx:
    toc: true
    number-sections: true
    toc-depth: 2
  pdf:
    pdf-engine: xelatex
    default-image-extension: png
    toc: true
    number-sections: true
    colorlinks: false
    toc-depth: 2
    lof: true
    lot: true
    documentclass: scrreprt
    papersize: a4
    fontsize: 12pt
    linestretch: 1.5
    babel-otherlangs: english
    cite-method: biblatex
    biblio-style: gost-numeric
    biblatexoptions:
      - backend=biber
      - langhook=extras
      - autolang=other*
    csquotes: true
    indent: true
    include-in-header:
      - file: _resources/tex/preamble.tex
