project:
  type: default
  output-dir: "_output"

format:
  html:
    toc: true
    number-sections: true
  pdf:
    toc: true
    number-sections: true
    include-in-header:
      - file: _resources/tex/preamble.tex
